### PR TITLE
Convert from Any::Moose to Moo

### LINKED ISSUE #25: tests fail on OBS [rt.cpan.org #80536]
https://rt.cpan.org/Ticket/Display.html?id=80536

    The tests should check for network connectivity and not assume it as a
    given.

### PR DESCRIPTION
**Pull request by haarg**
This is a refresh of #18.

I've converted it to use Types::Standard.  namespace::autoclean has been updated to work well with Moo since the last PR, so there was no need to touch that part.  I've also added Test::RequiresInternet to the tests to fix #25.

### CODE REVIEW

**Comment by xsawyerx** [comment]
Why not MooX::Types::MooseLike?

**Comment by xsawyerx** [comment]
Everything looks good except for:
* Not sure why `Types::Standard` and not `MooX::Types::MooseLike`.
* I don't like `is => 'lazy'`, it's not Moose-compliant.

**Comment by haarg** [comment]
Type::Tiny and Types::Standard are faster, more compatible, have a better API, and have a better namespace.  The Moo docs have been changed to recommend them over MooX::Types::MooseLike.  They can also be used with Moose without alteration.

I've added a commit to remove the `is => 'lazy'`.

**Comment by xsawyerx** [comment]
Merged, released. Thanks! :)

**Pull request merged**
